### ISSUE TITLE
Builder Interface

### ISSUE THREAD

**Issue by gtmacgregor** [kinetiq/Ether.Outcomes#1]
Hi!

Seems like a very useful library thanks for putting it out there! I am wondering why there is not a base builder interface to simplify adding the same message(s) and key(s) to both a successful and failure case?

`public interface IOutcomeBuilder : IOutcome {`
`   public void AddMessage(...)`
`   public void Success(...);`
`   public void Failure(...);`
`  ....`
`}`
Left out the generic version and functions for brevity... 

This way I can simplify the following situation in which I need to add the same set of messages and keys to either the success or failure
`IOutcome<int> o = null;`
`if (i == true) {`
`  o = Outcomes.Success<int>().AddMessage("This is a long message").AddKey("key1", val1).AddKey("key2", val2);`
`} else {`
`  o = Outcomes.Failure<int>().AddMessage("This is a long message").AddKey("key1", val1).AddKey("key2", val2);`
`}`
  
Could be changed  to
`IOutcomeBuilder<int> ob = i == true ? Outcomes.Success<int>() : Outcomes.Failure<int>()`
`ob.AddMessage("This is a long message").AddKey("key1", val1).AddKey("key2", val2);`

Is there a reason that is left out? If not I would be happy to add it in.

Thanks

 Glenn

**Comment by kinetiq** [comment]
Hi Glenn! I see the problem, I have not encountered that one yet.

What you're saying does make sense, my concern is that you would lose the success/failure-specific parts of the builder API if you went that direction, since IOutcomeBuilder would not be able to return SuccessOutcomeBuilder or FailureOutcomeBuilder, respectively. 

I would like to handle this scenario, but in a way that does not make the API more confusing in failure scenarios. 

Any thoughts about handling that?

**Comment by kinetiq** [comment]
No response, so I'm closing this issue.
