### ISSUE TITLE
2.9.5 - Method not found exception is thrown when dependent function is called from within try-catch block

### ISSUE THREAD

**Issue by sportflier** [kinetiq/Ether.Outcomes#11]
I have an existing project which uses Ether.Outcomes 2.2.0, within which a value is returned  Outcomes.Failure<IEnumerable<T>>().WithMessage("some message") in a number of function call scenarios.  I call these functions from other methods and when I do so, I enclose these calls in try-catch blocks.

When I update my project to Ether.Outcomes 2.9.5, it still builds without errors, but when I try to run my application, where code is executed code like described above, an exception is thrown and caught within the try-catch block:

  Message=Method not found: 'Ether.Outcomes.Builder.SuccessOutcomeBuilder`1<!0> Ether.Outcomes.Builder.SuccessOutcomeBuilder`1.WithMessage(System.String)'.

**BUT** if I then modify so the call is no longer surrounded by a try-catch block, no exception is thrown.

This is very puzzling to me... it seems like a bug but maybe I'm not understanding something here?

It seems like this happens in every case but verifying that would take some extensive work with this project. I commented out the try-catch code on the first instance where this happened, that segment of code started working correctly, but a similar exception is thrown in the next instance where the try-catch pattern is used. If I switch back to Ether.Outcomes 2.2.0 everything works correctly again.

**Comment by kinetiq** [comment]
@sportflier Hey, thanks for using Outcomes. I haven't come across this issue before. I definitely use Outcomes inside of try/catch blocks constantly, both in Framework and Core... Let's see if we can figure this out.  

Researching this a bit, I found this: https://stackoverflow.com/questions/7578583/method-not-found-on-runtime ... which just talks about how this error means that somehow at runtime, you literally do not have the method or method signature you expected, and that usually means the wrong DLL was deployed or is otherwise being accessed.

I did a little digging into source control, and the signature for WithMessage _has_ changed since 2.2.0 - it used to have an optional paramList, but at some point that was moved into WithMessageFormat. That is actually a breaking change, so it probably should have triggered a major version. At any rate, this supports the theory that you are somehow still running against 2.2.0! 

So let's attack that issue first. Is it possible that you are developing against 2.9.5 but running against or deploying 2.2.0? Can you double check the version of the outcomes dll that this is actually running?

Always thrilled to hear from people who use my stuff. :)

**Comment by sportflier** [comment]
@kinetiq Thanks for the quick reply. You hit the nail on the head. I had to ininstall ether.outcomes (which according to Nuget was only referenced in one), then scrub the filesystem to remove ether.outcomes.dll from three projects (which had differing versions of the DLL), then add a reference back to all three (maybe just doing the latter would also have fixed). Nuget was indicating that ether.outcomes.dll was only referenced in my core library, but updating here wasn't updating the other projects, which were using the older version.

It's still something I don't quite understand because *my* code hasn't changed and will run correctly with either version... but glad you helped me get this updated.

This is one of my favorite helper libraries, btw. Kudos for the good work.

**Comment by kinetiq** [comment]
Glad to help. :) I have a bunch of utilities I've built up around it that I haven't published yet - fluent validation patterns, and a pattern for working with JSON. Maybe I will get on that if people are into it. :)
