### ISSUE TITLE
IOutcome<T> and WCF

### ISSUE THREAD

**Issue by patrickcbrown** [kinetiq/Ether.Outcomes#2]
Hi

   More of a question than issue, is there a way that the IOutcome<T> can be passed directly as the return code through WCF?  In my attempts so far the underlying type SuccessOutcomeBuilder~1 cannot be serialized.  Id like to code as your examples show Outcomes.Success<List<int>>().WithValue(ret)

Thanks,
Patrick

**Comment by kinetiq** [comment]
Hi Patrick, thanks for the question. I actually serialize it all the time with JSON, but I've never had to do with with WCF. There's nothing special about these classes though, and I suspect it's just a matter of adding the serializable attribute. I can do that and release an alpha build if that would help. :)

**Comment by patrickcbrown** [comment]
Hey Brian

   That would be awesome, it mentioned the DataContract attribute but I think serializable will work also.  Short of that I was wondering if there was another trick you used but this change would be much better.

Thanks,
Patrick

**Comment by kinetiq** [comment]
Alright... First off, I've just learned is that [Serializable] is not supported in .Net Standard, evidently the modern approach is to push serialization "up the stack" since there are a lot of really strong serialization libraries. However, it looks like I can make this work for the .Net 4 / .Net 4.5 versions, and I'm working on that, so stay tuned.

As for other options: I serialize Outcomes and use them in JavaScript all the time, and it works really well. In fact, I need to write some blog posts about it, because it's one of the best ways to use this thing. I use JSON.Net for that sometimes, but if you happen to be using MVC (doesn't seem like it), this extension method will let you return a JSON version of an Outcome directly from an Action, and use it right away in JavaScript:

` return someOutcome.ToJsonResult();`

Here's the extension method:

```
        /// <summary>
        /// Generates a JsonResult for an Outcome.
        /// </summary>
        public static JsonResult ToJsonResult(this IOutcome outcome, JsonRequestBehavior behavior = JsonRequestBehavior.DenyGet)
        {
            return new JsonResult
            {
                Data = outcome,
                ContentType = null,
                ContentEncoding = null,
                JsonRequestBehavior = behavior
            };
        }
```

However, assuming you're stuck with WCF,  check out this very old StackOverflow question: http://stackoverflow.com/questions/3118504/how-to-set-json-net-as-the-default-serializer-for-wcf-rest-service

Here they show you how to serialize to JSON ahead of time, transmit the JSON, and then (and this part it's a little hazy on but it's the same process in reverse) deserialize back to an instance on the other end. Clunky, but it would work if all else fails. 

I'm going to try to get this alpha out today, if you wouldn't mind testing it. :)

**Comment by kinetiq** [comment]
Alright, this is live. In nuGet Package Manager, on the updates tab, you will have to click the "Include prerelease" box to get the package, it is version  **2.8.2** 

2.8.1 is listed as an alpha, but it's actually stable, I've been using it in production.

This should work with the BinaryFormatter... Let me know how that goes!

**Comment by patrickcbrown** [comment]
Thanks for the fast turnaround.  This got us closer, unfortunately we ran into a KnownType issue with Ether.Outcomes.Builder take a look at (https://blogs.msdn.microsoft.com/youssefm/2009/04/22/understanding-known-types/) for a quick understanding if you are not familiar.  To make WCF work it looks like there are a few options:
  1. Switch away from the DataContractSerializer 
  2  Add a KnownType attribute in the library
  3.  Implement a DataContractResolver in each project that uses the library
  I don't think I'd be able to get switching from the DataContractSerializer through a design review at this stage of our projects life.

**Comment by kinetiq** [comment]
Drat.  Well tell you what, if you want to do a pull request and add in the data contract attributes, I will certainly accept it. :) It would probably be quite easy, you would probably only have to deal with OutcomeResult.cs

**Comment by patrickcbrown** [comment]
Hey Brian

   Ok cool, will do.

Thanks,
Patrick

**Comment by kinetiq** [comment]
Thought I would check in on this Patrick, are you still thinking about doing a pull request? Would love the contribution, I bet it would help some people.

**Comment by patrickcbrown** [comment]
Hi Brian

   Yep I'm planning on it, gotta get past a few more tasks before I can focus on it.

**Comment by kinetiq** [comment]
Can I assume that this fell off your radar Patrick? :)

**Comment by kinetiq** [comment]
Closing due to no response.
